/* eslint-disable no-unused-vars */
export enum QueryKeys {
  CalendarEventTypes = 'calendarEventTypes',
  Documents = 'documents',
  DocumentCategories = 'documentCategories',
  CalendarEvents = 'calendarEvents',
  HistoricMonthData = 'historicMonthData',
  YearlyHistoricData = 'yearlyHistoricData',
  JournalEntries = 'journalEntries',
  GetSpendingPotDropdownOptions = 'getSpendingPotDropdownOptions',
  GetAutomaticTransactions = 'getAutomaticTransactions',
  GetManagePotData = 'getManagePotData',
  GetSubscriptions = 'getSubscriptions',
  NotePages = 'notePages',
  NotePageDetails = 'notePageDetails',
  DashboardOverview = 'dashboardOverview',
  HistoricMonthsDropdownValues = 'historicMonthsDropdownValues',
  HomepageStats = 'homepage-stats',
  GetUnprocessedTransactions = 'getUnprocessedTransactions',
  ShoppingListItems = 'shoppingListItems',
  Tasks = 'tasks',
  TaskCategories = 'taskCategories',
  PotBreakdownData = 'potBreakdownData',
  ThisMonthTransactions = 'thisMonthTransactions',
  ShoppingListQuickAddItems = 'shoppingListQuickAddItems',
  AddMonthPotData = 'addMonthPotData',
  MonthlyPaymentsForMonth = 'monthlyPaymentsForMonth',
  GetAllPotData = 'getAllPotData',
  GetNotePagesAndFolders = 'getNotePagesAndFolders',
  TodaysMood = 'todaysMood',
  YearlyMoodData = 'yearlyMoodData',
  AvailableYears = 'availableYears',
  FitbitConnectionStatus = 'fitbitConnectionStatus',
  FitbitProfile = 'fitbitProfile',
  FitbitDailyActivity = 'fitbitDailyActivity',
  Assets = 'assets',
  AssetCategories = 'assetCategories'
}
